server:
  port: 8888
spring:
  datasource:
    username: root
    password: lxjlxt123
    url: jdbc:mysql://localhost:3306/education?characterEnconding=utf-8
  redis:
    port: 6379
    host: localhost

logging:
  level:
    com.stuffmanage: debug
